name: khilesh_prajapat
description: A Flutter HTTP Server app

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/banner.png
    - images/logo.png
