name: Flutter Android APK Build

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required NDK
        run: sdkmanager "ndk;27.0.12077973"

      - name: Ensure android folder exists
        run: mkdir -p $GITHUB_WORKSPACE/android

      - name: Set NDK version in local.properties
        run: echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_WORKSPACE/android/local.properties

      - name: Get Flutter dependencies
        working-directory: your_flutter_project   # अगर प्रोजेक्ट root में है तो इस लाइन को हटा दें
        run: flutter pub get

      - name: Flutter clean
        working-directory: your_flutter_project   # अगर प्रोजेक्ट root में है तो इस लाइन को हटा दें
        run: flutter clean

      - name: Build APK (release)
        working-directory: your_flutter_project   # अगर प्रोजेक्ट root में है तो इस लाइन को हटा दें
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: your_flutter_project/build/app/outputs/flutter-apk/app-release.apk  # root प्रोजेक्ट हो तो path अपडेट करें
